export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  PRODUCTS: '/products',
  PRODUCT_CATEGORIES: '/products/categories',
  ORDERS: '/orders',
  INVOICES: '/invoices',
  ANALYTICS: '/analytics',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  HELP: '/help',
  FORBIDDEN: '/403',
  SERVER_ERROR: '/500',
  BAD_REQUEST: '/400',
  SERVICE_UNAVAILABLE: '/503',
  ERRORS: '/errors',
  NOT_FOUND: '*',
} as const;
